version: "3.9"
services:
  microservice:
    build: ./microservice
    restart:
      on-failure
    expose:
      - "3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - microservice
    ports:
      - "4000:4000"
